version: "3"

services:
  zed:
    build: .

    expose:
      - "8080"

    ports:
      - "8080:8080"

    depends_on:
      - zeddb

    environment:
      DATABASE_HOST: zeddb
      DATABASE_NAME: zed
      DATABASE_USER: zed_robot
      DATABASE_PASSWORD: "z3dr0b0t"

  zeddb:
    image: postgres:11

    volumes:
      # Volume for startup scripts. Note this willonly run if there is nothing in /var/lib/postgresql/data
      - ./devdatabase/db-init-scripts:/docker-entrypoint-initdb.d

      # Volume for persistance between runs. Uncomment if you wish to retain data.
      # - ./devdatabase/volume:/var/lib/postgresql/data

    expose:
      - "5432"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01
